ingress:
  hosts:
    - host: glpi.opicloud-ohe-dev-osc-euw2-wapp-02.k8s.dev.opicloud.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - glpi.opicloud-ohe-dev-osc-euw2-wapp-02.k8s.dev.opicloud.fr
    secretName: glpi
